### ISSUE TITLE
Add some console output

### ISSUE THREAD

**Issue by stuartcusackie** [justbetter/statamic-image-optimize#10]
I'm just waiting on an `optimize:images` job to finish, but I'm not sure if it is still running or how much is left to process.

Can we get some console output when running this command? I think it would mean removing the 'Actions' class and moving the code to the command, but then we have to consider queues as well.

Ideally:
- Show the total assets to be processed
- Show the current asset processing.
- Similar output to php please assets:generate-presets

I can look into a PR for this at a later date if you like the idea.

UPDATE: It seems the job finished 10 minutes ago but the command line never updated. SSH console frozen.

Thanks!

**Comment by kevinmeijer97** [comment]
Hi,
Currently it's only possible to see what your progress is if you're making use of the queue in combination with something like Horizon to check your jobs.

Nonetheless i do agree with you that, when not running a queue, there should be a verbose option to show the progress through the CLI.
On top of that i would like to integrate an admin page in the CP where you can start and track progress of the command.

I will look into this further soon, feel free to make a PR or other suggestions regarding this topic!
