### ISSUE TITLE
Suggestion: CP utility to resize all assets

### ISSUE THREAD

**Issue by stuartcusackie** [justbetter/statamic-image-optimize#3]
Hi, nice idea. In my case I have an old project with lots of large images, so I'm looking for a way to resize existing assets. A CP utility for queueing resize jobs on all assets would be cool, or maybe task scheduling to automatically check for large images on a regular basis.

A couple of other things:
- Ability to specify the queue connection / queue name to use for these jobs
- Your README file specifies the wrong package name for the composer install.

Thanks for reading!

**Comment by kevinmeijer97** [comment]
Hi, yes i was planning on adding a feature to optimise existing assets.
I will also be looking at the queue name specification and the README (thanks :) )

**Comment by stuartcusackie** [comment]
Thanks for handling this so quickly. I'm having some trouble though. The queue seems to be empty. I have tried the default queue (no config file changes) and I have tried a redis queue (name: imageoptimizer)

php artisan queue:work redis --queue=imageoptimize

The main job is being dispatched by the console command but it never seems to run. Is it just me?

**Comment by stuartcusackie** [comment]
Cool. Thanks for looking. BTW I don't think you'll need an EC2 instances, just an S3 bucket, or it might be easier to test on a Digital Ocean Space.
