### ISSUE TITLE
Asset not writeable when using an S3 bucket

### ISSUE THREAD

**Issue by kevinmeijer97** [justbetter/statamic-image-optimize#4]
#3 Inherited from

**Comment by stuartcusackie** [comment]
This is more of an S3 problem than EC2 - Should be same with Digital Ocean Spaces too.

**Comment by stuartcusackie** [comment]
This works great now. Thank you.

One small thing is that you have to clear the stache and the application cache afterwards in order for the filesizes in the asset containers to update. You might want to add those artisan / please commands to your command.
