### ISSUE TITLE
All meta data (alt text, focal points) lost

### ISSUE THREAD

**Issue by stuartcusackie** [justbetter/statamic-image-optimize#6]
Hi, I have just run the command on all existing images. All of my existing meta data: alt tags, focal points, and I imagine any asset blueprint fields were lost. Thankfully I made a backup before I ran the ResizeImages command. I have tried this twice with the same results.

I have ran your exact code manually and I have also dispatched a single ResizeImage job on a single asset and the meta was maintained in both cases. It only seems to be happening when using the bulk image resize command. Weird...

It seems like the job data is not being serialised correctly in the bulk resize job. I am experimenting with this now:

**Change this:**
```
public function resizeImages(AssetCollection $assetCollection): void
{
  $assetCollection->chunk($this->chunkSize)->each(function (AssetCollection $assets) {
    $assets->each(fn (Asset $asset) => $asset->isImage() ? ResizeImageJob::dispatch($asset) : '');
  });
 }
```

**To this:**
```
public function resizeImages(AssetCollection $assetCollection): void
{
  $assetCollection->chunk($this->chunkSize)->each(function (AssetCollection $assets) {
    $assets->each(function (Asset $asset) {
      if($asset->isImage()) {
        $asset->hydrate();
        ResizeImageJob::dispatch($asset);
      }
    });
  });
}

```

It works! I have created a PR.

**Comment by kevinmeijer97** [comment]
Thanks for looking into this! I did not account for this while creating the command, this fix seems to be the right way to go. For some reason Statamic already sends hydrated assets when triggering the resize job manually through the CP.

**Comment by stuartcusackie** [comment]
No problem at all. Thanks for the package!
